version: '3.1'

services:
  nginx:
    restart: always
    image: staticfloat/nginx-certbot
    ports:
      - 80:80/tcp
      - 443:443/tcp
    environment:
      CERTBOT_EMAIL: mayn13@gmail.com
      ENVSUBST_VARS: FQDN
      FQDN: "*.kimball.com.es"
    volumes:
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - drupal
  drupal:
    restart: unless-stopped
    image: drupal:8.9.13-apache
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "80"
    depends_on:
      - db
    volumes:
      - /home/ubuntu/bustibox/modules:/var/www/html/modules
      - /home/ubuntu/bustibox/profiles:/var/www/html/profiles
      - /home/ubuntu/bustibox/themes:/var/www/html/themes
      - /home/ubuntu/bustibox/sites:/var/www/html/sites
      - /home/ubuntu/bustibox/private_files:/var/www/bustibox_private

  db:
    restart: unless-stopped
    image: postgres:12.4-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
  letsencrypt: